dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0'
dotent: .env
wallets:
  from_key: ${PRIVATE_KEY}
